### ISSUE TITLE
Pen width over 10

### ISSUE THREAD

**Issue by NicolasCadieux** [NathanW2/MapInfo-to-QGIS-style-generator#1]
Great project,
Hi, pen width over 10 are HUGE in QGis. 1 to 7 = pixel, over 10 = points.
Nick

**Comment by NathanW2** [comment]
Thanks I'll check it out.

**Comment by NathanW2** [comment]
Note: Pixel size is still only handled using pixelsize / 3 until I can figure out a good way to handle pixel conversion.

**Comment by NicolasCadieux** [comment]
Hi Nathan,

I love your project.  It will be very useful.  I will beta test this all you want.  It your be nice if qgis could read the objectInfo directly from table column that could be created in MapInfo.  The reason for this is that I have a number of Pen and  Brush styles that are based on query from two columns.  ex: secondary roads can be paved or unpaved.  Of course, I could also create a new column that would combine this information...

Do you know of anything that can convert .wor to .qgs project file?

Nick.
