### ISSUE TITLE
“mapinfo qgis style generator: error message

### ISSUE THREAD

**Issue by image80** [NathanW2/MapInfo-to-QGIS-style-generator#3]
Hello,

I just posted a message on the qgis mailing list but it may be more appropriate to post s something here.  I'm working with mapinfo 12.0 , qgis 2.6 on windows 7 32 bits. My .tab layer is a complex POINT layer with a complex symbology (variables of shape, colour,etc.)

1/ Via my prompt command, when i ran the "ogrinfo -al" command, i get this following informations about features of the .TAB file. We can indeed notice that the Styleattribute column containing the OGR style string.The name of this field is Style.

![ss_ogrinfo](https://cloud.githubusercontent.com/assets/7910636/6059000/45c034dc-ad2d-11e4-9135-1c7692f1be15.JPG)

2/ But in a 2nd time, when i execute the plugin, i get again an error message.  The current structure of my command is : python mapinfoToQgis.py pathINPUT.Tab pathOUTPUT.qml  -c Style --UseMapInfo
The error message seems to say : "Variable or field Style not defined".

![ss_plugin_error_message](https://cloud.githubusercontent.com/assets/7910636/6059014/5699fcd4-ad2d-11e4-87d6-393096b92342.JPG)

i'm really sorry to disturb you. if you have any idea to fix this problem, it would be a pleasure and very usefull for my job.

Thank you very much.

**Comment by m-kuhn** [comment]
@NathanW2 FYI: http://gis.stackexchange.com/a/217959/9839
